[package]
name = "geyserbench"

version = "1.1.0"

edition = "2021"

[dependencies]
yellowstone-grpc-proto = "9.0.0"
yellowstone-grpc-client = "9.0.0"
tokio-stream = "0.1.17"

prost = "0.13.1"
prost-types = "0.13.3"
prost_011 = { package = "prost", version = "0.11.9" }

serde = "1.0.217"
toml = "0.8.20"
env_logger = "0.11.6"
tokio = { version = "1.43.0", features = ["full"] }
tonic = "0.12.3"
log = "0.4.25"
futures = "0.3.31"
futures-util = "0.3.31"
bs58 = "0.5.1"
bytes = "1.10.0"

lazy_static = "1.5.0"
solana-entry = "^2"
solana-sdk = "^2"
solana-transaction-status = "^2"
bincode = "1.3.3"

[build-dependencies]
anyhow = "1.0.62"
tonic-build = "0.12.3"

protobuf-src = "1.1.0"

